# Generated by Django 5.0.4 on 2024-05-09 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagsstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='quantity',
        ),
    ]
